'use client'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { isConfigured, supabase } from '@/lib/supabase/client'

type Track='creator'|'social'; type Room={id:string;name:string;track:Track;daily_target:number}; type Task={id:string;title:string;detail:string|null;platform:string|null;points:number}; type Proof={task_id:string;status:'submitted'|'approved'|'rejected'};
const creator=[{title:'Post an Instagram Story',detail:'Share something real from today',platform:'Instagram',points:10},{title:'Post a TikTok',detail:'Progress over polish',platform:'TikTok',points:15},{title:'Post on another platform',detail:'Choose the platform you want to grow',platform:'Other',points:15}];
const social=[{title:'Reach out to someone',detail:'Send a message, call, or voice note',platform:'Connection',points:10},{title:'Do one thing in public',detail:'Go somewhere, start something, show up',platform:'Out and about',points:15},{title:'Make a plan with someone',detail:'Put something on the calendar',platform:'Connection',points:15}];
export default function Home(){const db=useMemo(()=>isConfigured()?supabase():null,[]);const [user,setUser]=useState<any>(null),[room,setRoom]=useState<Room|null>(null),[tasks,setTasks]=useState<Task[]>([]),[proofs,setProofs]=useState<Proof[]>([]),[notice,setNotice]=useState(''),[mode,setMode]=useState<'auth'|'setup'|'room'>('auth'),[track,setTrack]=useState<Track>('creator');
useEffect(()=>{if(!db)return;db.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)loadRoom()});const {data:{subscription}}=db.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);if(s?.user)loadRoom()});return()=>subscription.unsubscribe()},[db]);
async function loadRoom(){if(!db)return;const {data}=await db.from('rooms').select('id,name,track,daily_target').limit(1).maybeSingle();if(!data){setMode('setup');return}setRoom(data);setMode('room');const [{data:roomTasks},{data:roomProofs}]=await Promise.all([db.from('room_tasks').select('id,title,detail,platform,points').eq('room_id',data.id).eq('active',true),db.from('proofs').select('task_id,status').eq('room_id',data.id).eq('task_date',new Date().toISOString().slice(0,10))]);setTasks(roomTasks||[]);setProofs(roomProofs||[])}
async function auth(e:FormEvent<HTMLFormElement>){if(!db)return;e.preventDefault();const form=new FormData(e.currentTarget),email=String(form.get('email')),password=String(form.get('password')),name=String(form.get('name'));const action=String(form.get('action'));const result=action==='signup'?await db.auth.signUp({email,password,options:{data:{display_name:name}}}):await db.auth.signInWithPassword({email,password});if(result.error)setNotice(result.error.message);else setNotice(action==='signup'?'Check your email to confirm your account.':'Welcome back.')}
async function createRoom(e:FormEvent<HTMLFormElement>){if(!db)return;e.preventDefault();const form=new FormData(e.currentTarget),name=String(form.get('room'));const {error}=await db.rpc('create_room_with_tasks',{room_name:name,chosen_track:track,target:Number(form.get('target')),task_rows:track==='creator'?creator:social});if(error){setNotice(error.message);return}await loadRoom()}
async function submitProof(task:Task){if(!db)return;const note=window.prompt(`Proof for “${task.title}” — paste a link or write a quick note:`);if(!note||!room||!user)return;const isLink=/^https?:\/\//.test(note);const {error}=await db.from('proofs').insert({room_id:room.id,task_id:task.id,user_id:user.id,task_date:new Date().toISOString().slice(0,10),kind:isLink?'link':'note',...(isLink?{link:note}:{note})});if(error)setNotice(error.message);else {setNotice('Proof sent. Your partner must confirm it before points count.');loadRoom()}}
if(!db)return <main className="welcome"><div><p className="eyebrow">DO IT TOGETHER</p><h1>Almost<br/><i>ready.</i></h1><p>Add the Supabase public URL and publishable key in <code>.env.local</code> to start your private room.</p></div></main>;
if(mode==='auth')return <main className="welcome"><div><p className="eyebrow">DO IT TOGETHER</p><h1>Show up.<br/><i>Together.</i></h1><p>Private daily accountability for posting online and showing up in real life.</p></div><form className="card" onSubmit={auth}><h2>Start your room</h2><input name="name" placeholder="Your name"/><input required name="email" type="email" placeholder="Email"/><input required name="password" type="password" placeholder="Password" minLength={6}/><button name="action" value="signup">Create account →</button><button className="link" name="action" value="signin">I already have an account</button>{notice&&<small>{notice}</small>}</form></main>;
if(mode==='setup')return <main className="welcome"><form className="card setup" onSubmit={createRoom}><p className="eyebrow">YOUR PRIVATE SPACE</p><h1>Start with<br/><i>the two of you.</i></h1><input required name="room" placeholder="Room name — e.g. The Posting Pact"/><div className="picks"><button type="button" onClick={()=>setTrack('creator')} className={track==='creator'?'picked':''}><b>Creator</b><span>Post consistently online</span></button><button type="button" onClick={()=>setTrack('social')} className={track==='social'?'picked':''}><b>Social life</b><span>Show up in real life</span></button></div><select name="target" defaultValue="10"><option value="10">10 points · one rep daily</option><option value="25">25 points · two reps daily</option><option value="40">40 points · three reps daily</option></select><button>Create my room →</button>{notice&&<small>{notice}</small>}</form></main>;
const confirmed=proofs.filter(p=>p.status==='approved').reduce((n,p)=>n+(tasks.find(t=>t.id===p.task_id)?.points||0),0);const seconds=Math.max(0,Math.floor((new Date(new Date().setHours(24,0,0,0)).getTime()-Date.now())/1000));const time=`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
return <main className="dashboard"><header><b>↗ <span>do it<br/>together</span></b><p>{room?.track==='creator'?'CREATOR ROOM':'SOCIAL LIFE ROOM'} · {room?.name}</p><button className="link" onClick={()=>db.auth.signOut()}>Sign out</button></header><section className="hero"><div><p className="eyebrow">TODAY’S SHARED TARGET</p><h1>{room?.daily_target} points<br/><i>before midnight.</i></h1><p>Both of you must hit the target and confirm each other’s proof for today’s points to bank.</p></div><div className="count"><small>TIME LEFT</small><strong>{time}</strong><span>Check in with your partner before the clock resets.</span></div></section><section className="progress"><b>{confirmed}/{room?.daily_target} confirmed points</b><span>{confirmed>=Number(room?.daily_target)?'Target reached — keep it going.':'No points count until your partner approves proof.'}</span></section><section><p className="eyebrow">YOUR DAILY REPS</p><h2>What are you showing up for?</h2>{tasks.map(task=>{const proof=proofs.find(p=>p.task_id===task.id);return <article className="task" key={task.id}><div><b>{task.title}</b><small>{task.detail}</small><em>{task.points} points</em></div>{proof?<span className={proof.status}>{proof.status==='approved'?'Confirmed ✓':'Waiting for partner'}</span>:<button onClick={()=>submitProof(task)}>Submit proof →</button>}</article>})}</section>{notice&&<div className="toast">{notice}</div>}</main>}
